### ISSUE TITLE
OperationalError at /en/admin/cms/page/add-plugin/  no such table: cmsplugin_soundcloud_soundcloud

### ISSUE THREAD

**Issue by oedicardia** [misli/cmsplugin-soundcloud#2]
Hi,
I am trying to get this plugin to work. After a few fixes that I could handle I came across this error:

`OperationalError at /en/admin/cms/page/add-plugin/
no such table: cmsplugin_soundcloud_soundcloud` 

which I can't get my head around.

Here are the fixes I did:
![image](https://user-images.githubusercontent.com/35580621/118146535-ff422980-b40e-11eb-88de-b033177b7b54.png)

I am not sure issue is triggered by the fixes I did and if a quick fix can be applied. 

Bellow is the traceback.
Thanks.

```
Request Method: POST
Request URL: http://127.0.0.1:8000/en/admin/cms/page/add-plugin/?placeholder_id=21&plugin_type=SoundCloudPlugin&cms_path=/en/music/?structure&plugin_language=en

Django Version: 3.1.8
Python Version: 3.9.4
Installed Applications:
['djangocms_admin_style',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.admin',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'django.contrib.messages',
 'cms',
 'menus',
 'sekizai',
 'treebeard',
 'djangocms_text_ckeditor',
 'filer',
 'easy_thumbnails',
 'djangocms_bootstrap4',
 'djangocms_bootstrap4.contrib.bootstrap4_alerts',
 'djangocms_bootstrap4.contrib.bootstrap4_badge',
 'djangocms_bootstrap4.contrib.bootstrap4_card',
 'djangocms_bootstrap4.contrib.bootstrap4_carousel',
 'djangocms_bootstrap4.contrib.bootstrap4_collapse',
 'djangocms_bootstrap4.contrib.bootstrap4_content',
 'djangocms_bootstrap4.contrib.bootstrap4_grid',
 'djangocms_bootstrap4.contrib.bootstrap4_jumbotron',
 'djangocms_bootstrap4.contrib.bootstrap4_link',
 'djangocms_bootstrap4.contrib.bootstrap4_listgroup',
 'djangocms_bootstrap4.contrib.bootstrap4_media',
 'djangocms_bootstrap4.contrib.bootstrap4_picture',
 'djangocms_bootstrap4.contrib.bootstrap4_tabs',
 'djangocms_bootstrap4.contrib.bootstrap4_utilities',
 'djangocms_file',
 'djangocms_icon',
 'djangocms_link',
 'djangocms_picture',
 'djangocms_style',
 'djangocms_googlemap',
 'djangocms_video',
 'tinymce',
 'djangocms_vimeo',
 'cmsplugin_soundcloud',
 'mySite']
Installed Middleware:
['cms.middleware.utils.ApphookReloadMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cms.middleware.user.CurrentUserMiddleware',
 'cms.middleware.page.CurrentPageMiddleware',
 'cms.middleware.toolbar.ToolbarMiddleware',
 'cms.middleware.language.LanguageCookieMiddleware']



Traceback (most recent call last):
  File "C:\Users\...\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\...\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (no such table: cmsplugin_soundcloud_soundcloud) was the direct cause of the following exception:
  File "C:\Users\...\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\...\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\...\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\...\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\...\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\...\lib\site-packages\django\views\decorators\clickjacking.py", line 33, in wrapped_view
    resp = view_func(*args, **kwargs)
  File "C:\Users\...\lib\site-packages\cms\admin\placeholderadmin.py", line 341, in add_plugin
    response = plugin_instance.add_view(request)
  File "C:\Users\...\lib\site-packages\django\contrib\admin\options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\...\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\...\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\...\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\...\lib\site-packages\django\contrib\admin\options.py", line 1580, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\...\lib\site-packages\cmsplugin_soundcloud\cms_plugins.py", line 27, in save_model
    return super(SoundCloudPlugin, self).save_model(request, obj, form, change)
  File "C:\Users\...\lib\site-packages\cms\plugin_base.py", line 335, in save_model
    return super().save_model(request, obj, form, change)
  File "C:\Users\...\lib\site-packages\django\contrib\admin\options.py", line 1093, in save_model
    obj.save()
  File "C:\Users\...\lib\site-packages\cms\models\pluginmodel.py", line 265, in save
    self.add_root(instance=self)
  File "C:\Users\...\lib\site-packages\treebeard\mp_tree.py", line 617, in add_root
    return MP_AddRootHandler(cls, **kwargs).process()
  File "C:\Users\...\lib\site-packages\treebeard\mp_tree.py", line 335, in process
    newobj.save()
  File "C:\Users\...\lib\site-packages\cms\models\pluginmodel.py", line 267, in save
    super().save(*args, **kwargs)
  File "C:\Users\...\lib\site-packages\django\db\models\base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\...\lib\site-packages\django\db\models\base.py", line 790, in save_base
    updated = self._save_table(
  File "C:\Users\...\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\...\lib\site-packages\django\db\models\base.py", line 933, in _do_insert
    return manager._insert(
  File "C:\Users\...\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\...\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\...\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\...\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\...\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\...\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\...\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\...\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\...\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\...\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /en/admin/cms/page/add-plugin/
Exception Value: no such table: cmsplugin_soundcloud_soundcloud
```

**Comment by oedicardia** [comment]
It turns out that migrations had not being performed at all. At some point they did after running `./manage.py makemigrations cmsplugin_soundcloud` and then `./manage.py migrate`. The plugin worked as intended but when attempting to modifying the model.py the migrations have worked a few times and then refuse to take into account editing about the `self.title = properties['title'] ` in method `load_data()`. Other editing in the SoundCloud(CMSPlugin) class but outside the methods are taken into account. So I suspect there is something not fully stable about the way this plugin is migrated.
